// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLyOxi_cbr7DDSsjkOBsYTnbzSGcMTxSM',
    appId: '1:46737009702:web:22465b5c608eeffaa6cae7',
    messagingSenderId: '46737009702',
    projectId: 'dreamacademy-example',
    authDomain: 'dreamacademy-example.firebaseapp.com',
    storageBucket: 'dreamacademy-example.appspot.com',
    measurementId: 'G-N13PKGVSYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArb3QRzBI2aeMZkqo5Gb66PB_AjzRM2ZM',
    appId: '1:46737009702:android:d5b6a757f49e050ca6cae7',
    messagingSenderId: '46737009702',
    projectId: 'dreamacademy-example',
    storageBucket: 'dreamacademy-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJEISuuNfZkYmz7aBQIZV3gjZRPanUT4',
    appId: '1:46737009702:ios:c3dd6a5821f8e18ea6cae7',
    messagingSenderId: '46737009702',
    projectId: 'dreamacademy-example',
    storageBucket: 'dreamacademy-example.appspot.com',
    iosBundleId: 'com.example.daAdministrator',
  );

}